# Generated by Django 2.2.5 on 2019-09-22 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=126)),
                ('description', models.TextField()),
                ('parent_category', models.ManyToManyField(blank=True, default=None, related_name='child_categories', to='ke_platform.Category', verbose_name='Parent categories')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=126)),
                ('description', models.TextField()),
                ('amount', models.IntegerField()),
                ('price', models.FloatField()),
                ('active', models.BooleanField()),
                ('categories', models.ManyToManyField(related_name='product_categories', related_query_name='product_categories', to='ke_platform.Category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=126)),
                ('description', models.TextField()),
                ('image_url', models.CharField(blank=True, max_length=402, null=True)),
            ],
            options={
                'verbose_name': 'Shop',
                'db_table': 'shops',
            },
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_imgs')),
                ('product_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Images', related_query_name='images', to='ke_platform.Product')),
            ],
        ),
    ]
