# Generated by Django 2.2.5 on 2019-09-22 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ke_platform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent_category',
            field=models.ManyToManyField(blank=True, default=None, related_name='parents', related_query_name='parents', to='ke_platform.Category', verbose_name='Parent Categories'),
        ),
        migrations.AlterModelTable(
            name='category',
            table='categories',
        ),
        migrations.AlterModelTable(
            name='product',
            table='products',
        ),
    ]
