# Generated by Django 2.2.5 on 2019-09-22 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ke_platform', '0002_auto_20190922_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='image_url',
        ),
        migrations.AddField(
            model_name='shop',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to='shop_images/'),
        ),
    ]
