# Generated by Django 2.2.5 on 2019-09-22 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ke_platform', '0003_auto_20190922_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='shop_images/'),
        ),
    ]
