# Generated by Django 2.2.5 on 2019-09-23 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ke_platform', '0004_auto_20190922_2329'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductImages',
            new_name='ProductImage',
        ),
    ]
