# Generated by Django 2.2.5 on 2019-09-23 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ke_platform', '0005_auto_20190923_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent_category',
            field=models.ManyToManyField(blank=True, related_name='children', related_query_name='child', to='ke_platform.Category', verbose_name='Parent Categories'),
        ),
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(related_name='products', related_query_name='product', to='ke_platform.Category'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', related_query_name='image', to='ke_platform.Product'),
        ),
    ]
