# Generated by Django 2.2.5 on 2019-09-23 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ke_platform', '0007_auto_20190923_2239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='orders',
            new_name='orders_num',
        ),
    ]
