# Generated by Django 2.2.5 on 2019-09-24 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ke_platform', '0011_auto_20190923_2354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product',
            new_name='shops',
        ),
    ]
