# Generated by Django 2.2.5 on 2019-09-24 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ke_platform', '0012_auto_20190924_0001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='shops',
        ),
        migrations.CreateModel(
            name='ShopProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shops_n', to='ke_platform.Product')),
                ('shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_n', to='ke_platform.Shop')),
            ],
        ),
        migrations.AddField(
            model_name='shop',
            name='products',
            field=models.ManyToManyField(related_name='shops', related_query_name='shop', through='ke_platform.ShopProduct', to='ke_platform.Product'),
        ),
    ]
