# Generated by Django 2.2.5 on 2019-09-18 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("KE_test", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="shop",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        )
    ]
