# Generated by Django 2.2.5 on 2019-09-18 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("KE_test", "0002_auto_20190918_1313")]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Product", "verbose_name_plural": "Products"},
        ),
        migrations.AlterModelOptions(
            name="productimage",
            options={
                "verbose_name": "Product image",
                "verbose_name_plural": "Product images",
            },
        ),
        migrations.AlterModelOptions(
            name="shop",
            options={"verbose_name": "Shop", "verbose_name_plural": "Shops"},
        ),
        migrations.AddField(
            model_name="product", name="active", field=models.BooleanField(default=True)
        ),
        migrations.AddField(
            model_name="product",
            name="orders",
            field=models.IntegerField(default=0, verbose_name="number of orders"),
        ),
    ]
