# Generated by Django 2.2.5 on 2019-09-18 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("KE_test", "0003_auto_20190918_1518")]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="subcategory",
            field=models.ManyToManyField(
                related_name="subcategories",
                to="KE_test.Category",
                verbose_name="subcategory",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ManyToManyField(
                related_name="categories",
                to="KE_test.Category",
                verbose_name="category",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(upload_to="product_images/"),
        ),
        migrations.AlterField(
            model_name="shop",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="shop",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="shop_images/"),
        ),
    ]
