# Generated by Django 4.0.1 on 2022-03-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0004_remove_product_category_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentCategory',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ManyToManyField(null=True, to='ecom.ParentCategory'),
        ),
    ]
