# Generated by Django 4.0.1 on 2022-03-24 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0005_parentcategory_category_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ManyToManyField(to='ecom.ParentCategory'),
        ),
    ]
