# Generated by Django 2.2.5 on 2019-09-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('imageURL', models.URLField()),
            ],
        ),
    ]
