# Generated by Django 2.2.5 on 2019-09-18 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop',
            options={'verbose_name': 'Shop', 'verbose_name_plural': 'Shops'},
        ),
        migrations.AlterField(
            model_name='shop',
            name='description',
            field=models.TextField(max_length=500, verbose_name='Description of shop'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='imageURL',
            field=models.URLField(verbose_name='Shop image'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='title',
            field=models.TextField(max_length=100, verbose_name='Title'),
        ),
    ]
