# Generated by Django 2.2.5 on 2019-09-18 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_auto_20190918_0921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='imageURL',
        ),
        migrations.AddField(
            model_name='shop',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to='shop_images/', verbose_name='Shop image'),
        ),
    ]
