# Generated by Django 2.2.5 on 2019-09-17 15:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=100)),
                ('description', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('amount', models.IntegerField()),
                ('price', models.FloatField()),
                ('images', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), size=10)),
                ('categories', models.ManyToManyField(to='products.Category')),
            ],
        ),
    ]
