# Generated by Django 2.2.5 on 2019-09-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent_category',
            field=models.ManyToManyField(default=None, null=True, related_name='_category_parent_category_+', to='products.Category'),
        ),
    ]
